language: php

php:
    - 7.1

install:
    # install local dependencies
    - composer install

before_scripts:
    # exit when any command fails
    - set -e

script:
    # static checks
    - composer check-cs
    - composer phpstan

    # build prefixed version
    - bin/console compile

    # test generated version
    - php rector.phar -vvv

notifications:
    email: false
