language: php

php:
    - 7.1

install:
    # install local dependencies
    - composer install

script:
    # static checks
    - composer check-cs
    - composer phpstan

    # build prefixed version
    - bin/console compile

    # test generated version
    - tmp/rector.phar -vvv

notifications:
    email: false
