language: php

php:
    - 7.1

install:
    # install local dependencies
    - composer install

script:
    # static checks
    - composer check-cs
    - composer phpstan

    # build prefixed version
    - bin/console compile

    # test generated version; the "|| ..." part is to fail travis, it passes silently on error without
    - ./rector.phar -vvv || { echo 'rector.phar failed'; exit 1; }

notifications:
    email: false
