language: php

php:
    - 7.1
    - 7.2

env:
    - FROM="from"

install:
    - composer install
    - composer create-project rector/rector $FROM

script:
    # static checks
    - composer check-cs
    - composer phpstan

    - bin/console prefix

    # test generated version
    - $FROM/bin/rector

notifications:
    email: false
