parameters:
    repository_url: 'https://github.com/rectorphp/rector.git'

    # tmp directory
    build_directory: "%kernel.project_dir%/tmp/build"

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Rector\Prefixer\:
        resource: "../src"

    Symfony\Component\Console\Application: ~
    Symfony\Component\Filesystem\Filesystem: ~
    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
